name: Crafty Navigator
description: Navigate using a compass and paper waypoints, no need for coords
version: 0.0.6
author: Ben Sergent V

main: com.challengercity.plugins.craftynavigator.CraftyNavigator
database: false

permissions:
  craftynavigator.user.*:
    description: Use Navigator
    default: true
    children:
      craftynavigator.user.setcompass: true
      craftynavigator.user.waypoint.*:
          description: Waypoint interfaces
          children:
            craftynavigator.user.waypoint.set: true
            craftynavigator.user.waypoint.clone: true
            craftynavigator.user.waypoint.craft: true
      
commands:
  navigator:
    description: Shows usage information for Navigator
    aliases: [nav, compass, cnav]