name: Navigator
description: Navigate using a compass and paper waypoints, no need for coords
version: 0.0.4
author: Ben Sergent V

main: com.challengercity.plugins.navigator.Navigator
database: false

permissions:
  navigator.user.*:
    description: Use Navigator
    default: true
    children:
      navigator.user.setcompass: true
      navigator.user.waypoint.*:
          description: Waypoint interfaces
          children:
            navigator.user.waypoint.set: true
            navigator.user.waypoint.clone: true
            navigator.user.waypoint.craft: true
      
commands:
  navigator:
    description: Shows usage information for Navigator
    aliases: [nav, compass]